DROP DATABASE IF EXISTS countries;
CREATE DATABASE countries;
USE countries;

-- ---------------------------------------------------------
-- -------------------------- SCHEMAS -------------------------
-- ---------------------------------------------------------

-- Country names in English
DROP TABLE IF EXISTS countries_en;
CREATE TABLE countries_en (
    id      SERIAL PRIMARY KEY,
    country VARCHAR(200) UNIQUE NOT NULL
);

-- Country names in French
DROP TABLE IF EXISTS countries_fr;
CREATE TABLE countries_fr (
    id      SERIAL PRIMARY KEY,
    country VARCHAR(200) UNIQUE NOT NULL
);

-- Country names in Spanish
DROP TABLE IF EXISTS countries_es;
CREATE TABLE countries_es (
    id      SERIAL PRIMARY KEY,
    country VARCHAR(200) UNIQUE NOT NULL
);

-- Country names in Chinese
DROP TABLE IF EXISTS countries_zh;
CREATE TABLE countries_zh (
    id      SERIAL PRIMARY KEY,
    country VARCHAR(200) UNIQUE NOT NULL
);

-- Country names in Russian
DROP TABLE IF EXISTS countries_ru;
CREATE TABLE countries_ru (
    id      SERIAL PRIMARY KEY,
    country VARCHAR(200) UNIQUE NOT NULL
);


-- ---------------------------------------------------------
-- -------------------------- DATA -------------------------
-- ---------------------------------------------------------

INSERT INTO countries_en (country)
VALUES ('Afghanistan'),
       ('Albania'),
       ('Algeria'),
       ('Andorra'),
       ('Angola'),
       ('Antigua and Barbuda'),
       ('Argentina'),
       ('Armenia'),
       ('Australia'),
       ('Austria'),
       ('Azerbaijan'),
       ('Bahamas'),
       ('Bahrain'),
       ('Bangladesh'),
       ('Barbados'),
       ('Belarus'),
       ('Belgium'),
       ('Belize'),
       ('Benin'),
       ('Bhutan'),
       ('Bolivia (Plurinational State of)'),
       ('Bosnia and Herzegovina'),
       ('Botswana'),
       ('Brazil'),
       ('Brunei Darussalam'),
       ('Bulgaria'),
       ('Burkina Faso'),
       ('Burundi'),
       ('Cabo Verde'),
       ('Cambodia'),
       ('Cameroon'),
       ('Canada'),
       ('Central African Republic'),
       ('Chad'),
       ('Chile'),
       ('China'),
       ('Colombia'),
       ('Comoros'),
       ('Congo'),
       ('Costa Rica'),
       ('Côte D''Ivoire'),
       ('Croatia'),
       ('Cuba'),
       ('Cyprus'),
       ('Czech Republic'),
       ('Democratic People''s Republic of Korea'),
       ('Democratic Republic of the Congo'),
       ('Denmark'),
       ('Djibouti'),
       ('Dominica'),
       ('Dominican Republic'),
       ('Ecuador'),
       ('Egypt'),
       ('El Salvador'),
       ('Equatorial Guinea'),
       ('Eritrea'),
       ('Estonia'),
       ('Eswatini'),
       ('Ethiopia'),
       ('Fiji'),
       ('Finland'),
       ('France'),
       ('Gabon'),
       ('Gambia (Republic of The)'),
       ('Georgia'),
       ('Germany'),
       ('Ghana'),
       ('Greece'),
       ('Grenada'),
       ('Guatemala'),
       ('Guinea'),
       ('Guinea Bissau'),
       ('Guyana'),
       ('Haiti'),
       ('Honduras'),
       ('Hungary'),
       ('Iceland'),
       ('India'),
       ('Indonesia'),
       ('Iran (Islamic Republic of)'),
       ('Iraq'),
       ('Ireland'),
       ('Israel'),
       ('Italy'),
       ('Jamaica'),
       ('Japan'),
       ('Jordan'),
       ('Kazakhstan'),
       ('Kenya'),
       ('Kiribati'),
       ('Kuwait'),
       ('Kyrgyzstan'),
       ('Lao People’s Democratic Republic'),
       ('Latvia'),
       ('Lebanon'),
       ('Lesotho'),
       ('Liberia'),
       ('Libya'),
       ('Liechtenstein'),
       ('Lithuania'),
       ('Luxembourg'),
       ('Madagascar'),
       ('Malawi'),
       ('Malaysia'),
       ('Maldives'),
       ('Mali'),
       ('Malta'),
       ('Marshall Islands'),
       ('Mauritania'),
       ('Mauritius'),
       ('Mexico'),
       ('Micronesia (Federated States of)'),
       ('Monaco'),
       ('Mongolia'),
       ('Montenegro'),
       ('Morocco'),
       ('Mozambique'),
       ('Myanmar'),
       ('Namibia'),
       ('Nauru'),
       ('Nepal'),
       ('Netherlands'),
       ('New Zealand'),
       ('Nicaragua'),
       ('Niger'),
       ('Nigeria'),
       ('North Macedonia'),
       ('Norway'),
       ('Oman'),
       ('Pakistan'),
       ('Palau'),
       ('Panama'),
       ('Papua New Guinea'),
       ('Paraguay'),
       ('Peru'),
       ('Philippines'),
       ('Poland'),
       ('Portugal'),
       ('Qatar'),
       ('Republic of Korea'),
       ('Republic of Moldova'),
       ('Romania'),
       ('Russian Federation'),
       ('Rwanda'),
       ('Saint Kitts and Nevis'),
       ('Saint Lucia'),
       ('Saint Vincent and the Grenadines'),
       ('Samoa'),
       ('San Marino'),
       ('Sao Tome and Principe'),
       ('Saudi Arabia'),
       ('Senegal'),
       ('Serbia'),
       ('Seychelles'),
       ('Sierra Leone'),
       ('Singapore'),
       ('Slovakia'),
       ('Slovenia'),
       ('Solomon Islands'),
       ('Somalia'),
       ('South Africa'),
       ('South Sudan'),
       ('Spain'),
       ('Sri Lanka'),
       ('Sudan'),
       ('Suriname'),
       ('Sweden'),
       ('Switzerland'),
       ('Syrian Arab Republic'),
       ('Tajikistan'),
       ('Thailand'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tonga'),
       ('Trinidad and Tobago'),
       ('Tunisia'),
       ('Turkey'),
       ('Turkmenistan'),
       ('Tuvalu'),
       ('Uganda'),
       ('Ukraine'),
       ('United Arab Emirates'),
       ('United Kingdom of Great Britain and Northern Ireland'),
       ('United Republic of Tanzania'),
       ('United States of America'),
       ('Uruguay'),
       ('Uzbekistan'),
       ('Vanuatu'),
       ('Venezuela, Bolivarian Republic of'),
       ('Viet Nam'),
       ('Yemen'),
       ('Zambia'),
       ('Zimbabwe');

INSERT INTO countries_fr (country)
VALUES ('Afghanistan'),
       ('Afrique du Sud'),
       ('Albanie'),
       ('Algérie'),
       ('Allemagne*'),
       ('Andorre'),
       ('Angola'),
       ('Antigua-et-Barbuda'),
       ('Arabie saoudite'),
       ('Argentine'),
       ('Arménie'),
       ('Australie'),
       ('Autriche'),
       ('Azerbaïdjan'),
       ('Bahamas'),
       ('Bahreïn'),
       ('Bangladesh'),
       ('Barbade'),
       ('Bélarus'),
       ('Belgique'),
       ('Belize'),
       ('Bénin'),
       ('Bhoutan'),
       ('Bolivie (État plurinational de)'),
       ('Bosnie-Herzégovine*'),
       ('Botswana'),
       ('Brésil'),
       ('Brunei Darussalam'),
       ('Bulgarie'),
       ('Burkina Faso'),
       ('Burundi'),
       ('Cabo Verde (République de)*'),
       ('Cambodge'),
       ('Cameroun'),
       ('Canada'),
       ('Chili'),
       ('Chine'),
       ('Chypre'),
       ('Colombie'),
       ('Comores'),
       ('Congo'),
       ('Costa Rica'),
       ('Côte D''Ivoire'),
       ('Croatie*'),
       ('Cuba'),
       ('Danemark'),
       ('Djibouti'),
       ('Dominique'),
       ('Égypte*'),
       ('El Salvador'),
       ('Émirats arabes unis'),
       ('Équateur'),
       ('Érythrée'),
       ('Espagne'),
       ('Estonie'),
       ('Eswatini'),
       ('États-Unis d''Amérique'),
       ('Éthiopie'),
       ('Fédération de Russie*'),
       ('Fidji'),
       ('Finlande'),
       ('France'),
       ('Gabon'),
       ('Gambie (République de)'),
       ('Géorgie'),
       ('Ghana'),
       ('Grèce'),
       ('Grenade'),
       ('Guatemala'),
       ('Guinée'),
       ('Guinée Bissau'),
       ('Guinée équatoriale'),
       ('Guyana*'),
       ('Haïti'),
       ('Honduras'),
       ('Hongrie'),
       ('Îles Marshall'),
       ('Îles Salomon'),
       ('Inde'),
       ('Indonésie*'),
       ('Iran (République islamique d'')'),
       ('Iraq'),
       ('Irlande'),
       ('Islande'),
       ('Israël'),
       ('Italie'),
       ('Jamaïque'),
       ('Japon'),
       ('Jordanie'),
       ('Kazakhstan'),
       ('Kenya'),
       ('Kirghizistan'),
       ('Kiribati'),
       ('Koweït'),
       ('Lesotho'),
       ('Lettonie'),
       ('Liban'),
       ('Libéria'),
       ('Libye*'),
       ('Liechtenstein'),
       ('Lituanie'),
       ('Luxembourg'),
       ('Macédoine du Nord'),
       ('Madagascar'),
       ('Malaisie*'),
       ('Malawi'),
       ('Maldives'),
       ('Mali'),
       ('Malte'),
       ('Maroc'),
       ('Maurice'),
       ('Mauritanie'),
       ('Mexique'),
       ('Micronésie (États fédérés de)'),
       ('Monaco'),
       ('Mongolie'),
       ('Monténégro*'),
       ('Mozambique'),
       ('Myanmar'),
       ('Namibie'),
       ('Nauru'),
       ('Népal'),
       ('Nicaragua'),
       ('Niger'),
       ('Nigéria'),
       ('Norvège'),
       ('Nouvelle-Zélande'),
       ('Oman'),
       ('Ouganda'),
       ('Ouzbékistan'),
       ('Pakistan'),
       ('Palaos'),
       ('Panama'),
       ('Papouasie-Nouvelle-Guinée'),
       ('Paraguay'),
       ('Pays-Bas'),
       ('Pérou'),
       ('Philippines'),
       ('Pologne'),
       ('Portugal'),
       ('Qatar'),
       ('République arabe syrienne*'),
       ('République centrafricaine'),
       ('République de Corée'),
       ('République de Moldova'),
       ('République démocratique du Congo*'),
       ('République démocratique populaire lao'),
       ('République dominicaine'),
       ('République populaire démocratique de Corée'),
       ('République tchèque*'),
       ('République-Unie de Tanzanie*'),
       ('Roumanie'),
       ('Royaume-Uni de Grande-Bretagne et d''Irlande du Nord'),
       ('Rwanda'),
       ('Saint-Kitts-et-Nevis'),
       ('Saint-Marin'),
       ('Saint-Vincent-et-les Grenadines'),
       ('Sainte-Lucie'),
       ('Samoa'),
       ('Sao Tomé-et-Principe'),
       ('Sénégal'),
       ('Serbie*'),
       ('Seychelles'),
       ('Sierra Leone'),
       ('Singapour*'),
       ('Slovaquie*'),
       ('Slovénie*'),
       ('Somalie'),
       ('Soudan'),
       ('Soudan du Sud*'),
       ('Sri Lanka'),
       ('Suède'),
       ('Suisse'),
       ('Suriname'),
       ('Tadjikistan'),
       ('Tchad'),
       ('Thaïlande'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tonga'),
       ('Trinité-et-Tobago'),
       ('Tunisie'),
       ('Turkménistan'),
       ('Turquie'),
       ('Tuvalu'),
       ('Ukraine'),
       ('Uruguay'),
       ('Vanuatu'),
       ('Venezuela (République bolivarienne du)'),
       ('Viet Nam'),
       ('Yémen*'),
       ('Zambie'),
       ('Zimbabwe');

INSERT INTO countries_es (country)
VALUES ('Afganistán'),
       ('Albania'),
       ('Alemania*'),
       ('Andorra'),
       ('Angola'),
       ('Antigua y Barbuda'),
       ('Arabia Saudita'),
       ('Argelia'),
       ('Argentina'),
       ('Armenia'),
       ('Australia'),
       ('Austria'),
       ('Azerbaiyán'),
       ('Bahamas'),
       ('Bahrein'),
       ('Bangladesh'),
       ('Barbados'),
       ('Belarús*'),
       ('Bélgica'),
       ('Belice'),
       ('Benin'),
       ('Bhután'),
       ('Bolivia (Estado Plurinacional de)'),
       ('Bosnia y Herzegovina*'),
       ('Botswana'),
       ('Brasil'),
       ('Brunei Darussalam'),
       ('Bulgaria'),
       ('Burkina Faso'),
       ('Burundi'),
       ('Cabo Verde*'),
       ('Camboya'),
       ('Camerún'),
       ('Canadá'),
       ('Chad'),
       ('Chile'),
       ('China'),
       ('Chipre'),
       ('Colombia'),
       ('Comoras'),
       ('Congo'),
       ('Costa Rica'),
       ('Côte d''Ivoire'),
       ('Croacia*'),
       ('Cuba'),
       ('Dinamarca'),
       ('Djibouti'),
       ('Dominica'),
       ('Ecuador'),
       ('Egipto*'),
       ('El Salvador'),
       ('Emiratos Árabes Unidos'),
       ('Eritrea'),
       ('Eslovaquia*'),
       ('Eslovenia *'),
       ('España'),
       ('Estados Unidos de América'),
       ('Estonia'),
       ('Eswatini'),
       ('Etiopía'),
       ('Federación de Rusia*'),
       ('Fiji'),
       ('Filipinas'),
       ('Finlandia'),
       ('Francia'),
       ('Gabón'),
       ('Gambia (República de)'),
       ('Georgia'),
       ('Ghana'),
       ('Granada'),
       ('Grecia'),
       ('Guatemala'),
       ('Guinea'),
       ('Guinea Bissau'),
       ('Guinea Ecuatorial'),
       ('Guyana*'),
       ('Haití'),
       ('Honduras'),
       ('Hungría'),
       ('India'),
       ('Indonesia*'),
       ('Irán (República Islámica del)'),
       ('Iraq'),
       ('Irlanda'),
       ('Islandia'),
       ('Islas Marshall'),
       ('Islas Salomón'),
       ('Israel'),
       ('Italia'),
       ('Jamaica'),
       ('Japón'),
       ('Jordania'),
       ('Kazajstán'),
       ('Kenya'),
       ('Kirguistán'),
       ('Kiribati'),
       ('Kuwait'),
       ('Lesotho'),
       ('Letonia'),
       ('Líbano'),
       ('Liberia'),
       ('Libia*'),
       ('Liechtenstein'),
       ('Lituania'),
       ('Luxemburgo'),
       ('Macedonia del Norte'),
       ('Madagascar'),
       ('Malasia*'),
       ('Malawi'),
       ('Maldivas'),
       ('Malí'),
       ('Malta'),
       ('Marruecos'),
       ('Mauricio'),
       ('Mauritania'),
       ('México'),
       ('Micronesia (Estados Federados de)'),
       ('Mónaco'),
       ('Mongolia'),
       ('Montenegro*'),
       ('Mozambique'),
       ('Myanmar'),
       ('Namibia'),
       ('Nauru'),
       ('Nepal'),
       ('Nicaragua'),
       ('Niger'),
       ('Nigeria'),
       ('Noruega'),
       ('Nueva Zelandia'),
       ('Omán'),
       ('Países Bajos'),
       ('Pakistán'),
       ('Palau'),
       ('Panamá'),
       ('Papua Nueva Guinea'),
       ('Paraguay'),
       ('Perú'),
       ('Polonia'),
       ('Portugal'),
       ('Qatar'),
       ('Reino Unido de Gran Bretaña e Irlanda del Norte'),
       ('República Árabe Siria*'),
       ('República Centroafricana'),
       ('República Checa*'),
       ('República de Corea'),
       ('República de Moldova'),
       ('República Democrática del Congo*'),
       ('República Democrática Popular Lao'),
       ('República Dominicana'),
       ('República Popular Democrática de Corea'),
       ('República Unida de Tanzanía*'),
       ('Rumania'),
       ('Rwanda'),
       ('Saint Kitts y Nevis'),
       ('Samoa'),
       ('San Marino'),
       ('San Vicente y las Granadinas'),
       ('Santa Lucía'),
       ('Santo Tomé y Príncipe'),
       ('Senegal'),
       ('Serbia*'),
       ('Seychelles'),
       ('Sierra Leona'),
       ('Singapur*'),
       ('Somalia'),
       ('Sri Lanka'),
       ('Sudáfrica'),
       ('Sudán'),
       ('Sudán del Sur*'),
       ('Suecia'),
       ('Suiza'),
       ('Suriname'),
       ('Tailandia'),
       ('Tayikistán'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tonga'),
       ('Trinidad yTobago'),
       ('Túnez'),
       ('Turkmenistán'),
       ('Turquía'),
       ('Tuvalu'),
       ('Ucrania'),
       ('Uganda'),
       ('Uruguay'),
       ('Uzbekistán'),
       ('Vanuatu'),
       ('Venezuela (República Bolivariana de)'),
       ('Viet Nam'),
       ('Yemen*'),
       ('Zambia'),
       ('Zimbabwe');

INSERT INTO countries_zh (country)
VALUES ('阿尔巴尼亚'),
       ('阿尔及利亚'),
       ('阿富汗'),
       ('阿根廷'),
       ('阿拉伯联合酋长国'),
       ('阿拉伯叙利亚共和国*'),
       ('阿曼'),
       ('阿塞拜疆'),
       ('埃及*'),
       ('埃塞俄比亚'),
       ('爱尔兰'),
       ('爱沙尼亚'),
       ('安道尔'),
       ('安哥拉'),
       ('安提瓜和巴布达'),
       ('奥地利'),
       ('澳大利亚'),
       ('巴巴多斯'),
       ('巴布亚新几内亚'),
       ('巴哈马'),
       ('巴基斯坦'),
       ('巴拉圭'),
       ('巴林'),
       ('巴拿马'),
       ('巴西'),
       ('白俄罗斯*'),
       ('保加利亚'),
       ('北马其顿*'),
       ('贝宁'),
       ('比利时'),
       ('秘鲁'),
       ('冰岛'),
       ('波兰'),
       ('波斯尼亚和黑塞哥维那*'),
       ('伯利兹'),
       ('博茨瓦纳'),
       ('不丹'),
       ('布基纳法索'),
       ('布隆迪'),
       ('朝鲜民主主义人民共和国'),
       ('赤道几内亚'),
       ('大不列颠及北爱尔兰联合王国'),
       ('大韩民国'),
       ('丹麦'),
       ('德国*'),
       ('东帝汶'),
       ('多哥'),
       ('多米尼加'),
       ('多米尼克'),
       ('多民族玻利维亚国'),
       ('俄罗斯联邦*'),
       ('厄瓜多尔'),
       ('厄立特里亚'),
       ('法国'),
       ('菲律宾'),
       ('斐济'),
       ('芬兰'),
       ('佛得角'),
       ('冈比亚'),
       ('刚果（布）'),
       ('刚果民主共和国*'),
       ('哥伦比亚'),
       ('哥斯达黎加'),
       ('格林纳达'),
       ('格鲁吉亚'),
       ('古巴'),
       ('圭亚那'),
       ('哈萨克斯坦'),
       ('海地'),
       ('荷兰'),
       ('黑山 *'),
       ('洪都拉斯'),
       ('基里巴斯'),
       ('吉布提'),
       ('吉尔吉斯斯坦'),
       ('几内亚'),
       ('几内亚比绍'),
       ('加拿大'),
       ('加纳'),
       ('加蓬'),
       ('柬埔寨'),
       ('捷克*'),
       ('津巴布韦'),
       ('喀麦隆'),
       ('卡塔尔'),
       ('科摩罗'),
       ('科特迪瓦'),
       ('科威特'),
       (' 克罗地亚*'),
       ('肯尼亚'),
       ('拉脱维亚'),
       ('莱索托'),
       ('老挝人民民主共和国'),
       ('黎巴嫩'),
       ('立陶宛'),
       ('利比里亚*'),
       ('利比亚*'),
       ('列支敦士登'),
       ('卢森堡'),
       ('卢旺达'),
       ('罗马尼亚'),
       ('马达加斯加'),
       ('马尔代夫'),
       ('马耳他'),
       ('马拉维'),
       ('马来西亚*'),
       ('马里'),
       ('马绍尔群岛'),
       ('毛里求斯'),
       ('毛里塔尼亚'),
       ('美利坚合众国'),
       ('蒙古'),
       ('孟加拉国'),
       ('密克罗尼西亚联邦'),
       ('缅甸'),
       ('摩尔多瓦共和国'),
       ('摩洛哥'),
       ('摩纳哥'),
       ('莫桑比克'),
       ('墨西哥'),
       ('纳米比亚'),
       ('南非'),
       ('南苏丹'),
       ('瑙鲁'),
       ('尼泊尔'),
       ('尼加拉瓜'),
       ('尼日尔'),
       ('尼日利亚'),
       ('挪威'),
       ('帕劳'),
       ('葡萄牙'),
       ('日本'),
       ('瑞典'),
       ('瑞士'),
       ('萨尔瓦多'),
       ('萨摩亚'),
       ('塞尔维亚*'),
       ('塞拉利昂'),
       ('塞内加尔'),
       ('塞浦路斯'),
       ('塞舌尔'),
       ('沙特阿拉伯'),
       ('圣多美和普林西比'),
       ('圣基茨和尼维斯'),
       ('圣卢西亚'),
       ('圣马力诺'),
       ('圣文森特和格林纳丁斯'),
       ('斯里兰卡'),
       ('斯洛伐克*'),
       ('斯洛文尼亚 *'),
       ('斯威士兰'),
       ('苏丹'),
       ('苏里南'),
       ('所罗门群岛'),
       ('索马里'),
       ('塔吉克斯坦'),
       ('泰国'),
       ('坦桑尼亚联合共和国*'),
       ('汤加'),
       ('特立尼达和多巴哥'),
       ('突尼斯'),
       ('图瓦卢'),
       ('土耳其'),
       ('土库曼斯坦'),
       ('瓦努阿图'),
       ('危地马拉'),
       ('委内瑞拉玻利瓦尔共和国'),
       ('文莱达鲁萨兰国'),
       ('乌干达'),
       ('乌克兰'),
       ('乌拉圭'),
       ('乌兹别克斯坦'),
       ('西班牙'),
       ('希腊'),
       ('新加坡*'),
       ('新西兰'),
       ('匈牙利'),
       ('牙买加'),
       ('亚美尼亚'),
       ('也门*'),
       ('伊拉克'),
       ('伊朗伊斯兰共和国'),
       ('以色列'),
       ('意大利'),
       ('印度'),
       ('印度尼西亚*'),
       ('约旦'),
       ('越南'),
       ('赞比亚'),
       ('乍得'),
       ('智利'),
       ('中非共和国'),
       ('中国');

INSERT INTO countries_ru (country)
VALUES ('Австралия'),
       ('Австрия'),
       ('Азербайджан'),
       ('Албания'),
       ('Алжир'),
       ('Ангола'),
       ('Андорра'),
       ('Антигуа и Барбуда'),
       ('Аргентина'),
       ('Армения'),
       ('Афганистан'),
       ('Багамские Острова'),
       ('Бангладеш'),
       ('Барбадос'),
       ('Бахрейн'),
       ('Беларусь*'),
       ('Белиз'),
       ('Бельгия'),
       ('Бенин*'),
       ('Болгария'),
       ('Боливия (Многонациональное Государство)*'),
       ('Босния и Герцеговина*'),
       ('Ботсвана'),
       ('Бразилия'),
       ('Бруней-Даруссалам'),
       ('Буркина-Фасо*'),
       ('Бурунди'),
       ('Бутан'),
       ('Вануату'),
       ('Венгрия'),
       ('Венесуэла (Боливарианская Республика)'),
       ('Вьетнам'),
       ('Габон'),
       ('Гаити'),
       ('Гайана*'),
       ('Гамбия'),
       ('Гана'),
       ('Гватемала'),
       ('Гвинея'),
       ('Гвинея-Бисау'),
       ('Германия*'),
       ('Гондурас'),
       ('Гренада'),
       ('Греция'),
       ('Грузия'),
       ('Дания'),
       ('Демократическая Республика Конго*'),
       ('Джибути'),
       ('Доминика'),
       ('Доминиканская Республика'),
       ('Египет*'),
       ('Замбия'),
       ('Зимбабве'),
       ('Израиль'),
       ('Индия'),
       ('Индонезия*'),
       ('Иордания'),
       ('Ирак'),
       ('Иран (Исламская Республика)*'),
       ('Ирландия'),
       ('Исландия'),
       ('Испания'),
       ('Италия'),
       ('Йемен*'),
       ('Кабо-Верде*'),
       ('Казахстан'),
       ('Камбоджа'),
       ('Камерун'),
       ('Канада'),
       ('Катар'),
       ('Кения'),
       ('Кипр'),
       ('Кирибати'),
       ('Китай'),
       ('Колумбия'),
       ('Коморские Острова'),
       ('Конго*'),
       ('Корейская Народно-Демократическая  Республика'),
       ('Коста-Рика'),
       ('Кот-д''Ивуар*'),
       ('Куба'),
       ('Кувейт'),
       ('Кыргызстан'),
       ('Лаосская Народно-Демократическая  Республика*'),
       ('Латвия'),
       ('Лесото'),
       ('Либерия'),
       ('Ливан'),
       ('Ливия*'),
       ('Литва'),
       ('Лихтенштейн'),
       ('Люксембург'),
       ('Маврикий'),
       ('Мавритания'),
       ('Мадагаскар*'),
       ('Малави'),
       ('Малайзия*'),
       ('Мали'),
       ('Мальдивские Острова'),
       ('Мальта'),
       ('Марокко'),
       ('Маршалловы Острова'),
       ('Мексика'),
       ('Микронезия (Федеративные Штаты)'),
       ('Мозамбик'),
       ('Монако'),
       ('Монголия'),
       ('Мьянма*'),
       ('Намибия'),
       ('Науру'),
       ('Непал'),
       ('Нигер'),
       ('Нигерия'),
       ('Нидерланды'),
       ('Никарагуа'),
       ('Новая Зеландия'),
       ('Норвегия'),
       ('Объединенная Республика Танзания*'),
       ('Объединенные Арабские Эмираты'),
       ('Оман'),
       ('Пакистан'),
       ('Палау'),
       ('Панама'),
       ('Папуа-Новая Гвинея'),
       ('Парагвай'),
       ('Перу'),
       ('Польша'),
       ('Португалия'),
       ('Республика Корея'),
       ('Республика Молдова'),
       ('Российская Федерация*'),
       ('Руанда'),
       ('Румыния'),
       ('Сальвадор'),
       ('Самоа'),
       ('Сан-Марино'),
       ('Сан-Томе и Принсипи'),
       ('Саудовская Аравия'),
       ('Северная Македония'),
       ('Сейшельские Острова'),
       ('Сенегал'),
       ('Сент-Винсент и Гренадины'),
       ('Сент-Китс и Невис*'),
       ('Сент-Люсия'),
       ('Сербия*'),
       ('Сингапур*'),
       ('Сирийская Арабская Республика*'),
       ('Словакия*'),
       ('Словения*'),
       ('Соединенное Королевство Великобритании  и Северной Ирландии'),
       ('Соединенные Штаты Америки'),
       ('Соломоновы Острова'),
       ('Сомали'),
       ('Судан'),
       ('Суринам'),
       ('Сьерра-Леоне '),
       ('Таджикистан'),
       ('Таиланд*'),
       ('Тимор-Лешти'),
       ('Того'),
       ('Тонга'),
       ('Тринидад и Тобаго'),
       ('Тувалу'),
       ('Тунис'),
       ('Туркменистан'),
       ('Турция'),
       ('Уганда'),
       ('Узбекистан'),
       ('Украина*'),
       ('Уругвай'),
       ('Фиджи'),
       ('Филиппины*'),
       ('Финляндия'),
       ('Франция'),
       ('Хорватия*'),
       ('Центральноафриканская Республика'),
       ('Чад'),
       ('Черногория*'),
       ('Чешская Республика*'),
       ('Чили'),
       ('Швейцария'),
       ('Швеция'),
       ('Шри-Ланка*'),
       ('Эквадор'),
       ('Экваториальная Гвинея'),
       ('Эритрея'),
       ('Эсватини'),
       ('Эстония'),
       ('Эфиопия'),
       ('Южная Африка*'),
       ('Южный Судан*'),
       ('Ямайка'),
       ('Япония');